version: "3"

services:
    srv-sql:
        image: mcr.microsoft.com/mssql/server:latest
        restart: unless-stopped
        environment:
            ACCEPT_EULA: 'Y'
            SA_PASSWORD: 'oHbn4FDxBL1nmHjHqau1'
            
    # This requires a Windows container host system.
    srv-aspnet:
        image: mcr.microsoft.com/dotnet/framework/aspnet:4.6.2
        restart: unless-stopped
        ports:
            - 8080:80
        depends_on:
            - srv-sql